# Generated by Django 4.2.10 on 2024-05-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
    ]
