"""
Django settings for TestAWSapp project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

import os #追記
import environ #追記

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .envファイルを読み込む
env = environ.Env() #追記
env.read_env(os.path.join(BASE_DIR, '.env')) #追記


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

#開発環境用
SECRET_KEY = env('SECRET_KEY')

DEBUG = True

ALLOWED_HOSTS = []

#本番環境用
'''
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Faulse

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS') 
'''


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 開発したアプリケーションの追加
    'AWSapp.apps.AwsappConfig',
    'django_bootstrap5',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TestAWSapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TestAWSapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases



    #開発環境用
DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'TestAWSapp',
        'USER': 'root',
        'PASSWORD': 'Pita1236',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



#本番環境用
'''
DATABASES = {
    'default': {
        'ENGINE': env('ENGINE'),  # データベースエンジン
        'NAME': env('NAME'),  # データベース名
        'USER': env('USER'),  # データベースユーザー
        'PASSWORD': env('PASSWORD'),  # データベースパスワード
        'HOST': env('HOST'),  # データベースホスト
        'PORT': env('PORT'),  # データベースポート
    }
}
'''    



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


'''
# AWS settings
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'


# Static files (CSS, JavaScript, Images)
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{env("AWS_STATIC_LOCATION")}/'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{env("AWS_MEDIA_LOCATION")}/'

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'AWSapp.storage_backends.MediaStorage'
'''

# メディアファイルのルートディレクトリ
MEDIA_ROOT = BASE_DIR / 'media'

# メディアファイルへのURL
MEDIA_URL = '/media/'

STATIC_URL = '/static/'


